module.exports = [
  {
    topicId: "arrays",
    title: "Arrays",
    description: "Core array techniques including two pointers, prefix sums, and sorting patterns.",
    order: 1,
    problems: [
      {
        problemId: "two-sum",
        title: "Two Sum",
        difficulty: "Easy",
        youtubeLink: "https://www.youtube.com/results?search_query=two+sum+leetcode+explanation",
        practiceLink: "https://leetcode.com/problems/two-sum/",
        articleLink: "https://www.geeksforgeeks.org/check-if-pair-with-given-sum-exists-in-array/",
      },
      {
        problemId: "maximum-subarray",
        title: "Maximum Subarray",
        difficulty: "Medium",
        youtubeLink: "https://www.youtube.com/results?search_query=maximum+subarray+kadane+algorithm",
        practiceLink: "https://leetcode.com/problems/maximum-subarray/",
        articleLink: "https://www.geeksforgeeks.org/largest-sum-contiguous-subarray/",
      },
      {
        problemId: "merge-intervals",
        title: "Merge Intervals",
        difficulty: "Medium",
        youtubeLink: "https://www.youtube.com/results?search_query=merge+intervals+leetcode+explanation",
        practiceLink: "https://leetcode.com/problems/merge-intervals/",
        articleLink: "https://www.geeksforgeeks.org/merging-intervals/",
      },
    ],
  },
  {
    topicId: "strings",
    title: "Strings",
    description: "String manipulation, maps, windows, and palindrome-oriented problem solving.",
    order: 2,
    problems: [
      {
        problemId: "valid-anagram",
        title: "Valid Anagram",
        difficulty: "Easy",
        youtubeLink: "https://www.youtube.com/results?search_query=valid+anagram+leetcode+explanation",
        practiceLink: "https://leetcode.com/problems/valid-anagram/",
        articleLink: "https://www.geeksforgeeks.org/check-whether-two-strings-are-anagram-of-each-other/",
      },
      {
        problemId: "longest-substring",
        title: "Longest Substring Without Repeating Characters",
        difficulty: "Medium",
        youtubeLink: "https://www.youtube.com/results?search_query=longest+substring+without+repeating+characters",
        practiceLink: "https://leetcode.com/problems/longest-substring-without-repeating-characters/",
        articleLink: "https://www.geeksforgeeks.org/length-of-the-longest-substring-without-repeating-characters/",
      },
      {
        problemId: "minimum-window",
        title: "Minimum Window Substring",
        difficulty: "Tough",
        youtubeLink: "https://www.youtube.com/results?search_query=minimum+window+substring+leetcode",
        practiceLink: "https://leetcode.com/problems/minimum-window-substring/",
        articleLink: "https://www.geeksforgeeks.org/find-the-smallest-window-in-a-string-containing-all-characters-of-another-string/",
      },
    ],
  },
  {
    topicId: "linked-list",
    title: "Linked List",
    description: "Pointer movement, reversal, cycle detection, and list restructuring.",
    order: 3,
    problems: [
      {
        problemId: "reverse-linked-list",
        title: "Reverse Linked List",
        difficulty: "Easy",
        youtubeLink: "https://www.youtube.com/results?search_query=reverse+linked+list+leetcode",
        practiceLink: "https://leetcode.com/problems/reverse-linked-list/",
        articleLink: "https://www.geeksforgeeks.org/reverse-a-linked-list/",
      },
      {
        problemId: "linked-list-cycle",
        title: "Linked List Cycle",
        difficulty: "Easy",
        youtubeLink: "https://www.youtube.com/results?search_query=linked+list+cycle+floyd+algorithm",
        practiceLink: "https://leetcode.com/problems/linked-list-cycle/",
        articleLink: "https://www.geeksforgeeks.org/detect-loop-in-a-linked-list/",
      },
      {
        problemId: "merge-k-lists",
        title: "Merge K Sorted Lists",
        difficulty: "Tough",
        youtubeLink: "https://www.youtube.com/results?search_query=merge+k+sorted+lists+leetcode",
        practiceLink: "https://leetcode.com/problems/merge-k-sorted-lists/",
        articleLink: "https://www.geeksforgeeks.org/merge-k-sorted-linked-lists/",
      },
    ],
  },
  {
    topicId: "trees",
    title: "Trees",
    description: "Traversal, recursion, breadth-first search, and binary tree design patterns.",
    order: 4,
    problems: [
      {
        problemId: "max-depth",
        title: "Maximum Depth of Binary Tree",
        difficulty: "Easy",
        youtubeLink: "https://www.youtube.com/results?search_query=maximum+depth+of+binary+tree",
        practiceLink: "https://leetcode.com/problems/maximum-depth-of-binary-tree/",
        articleLink: "https://www.geeksforgeeks.org/find-the-maximum-depth-or-height-of-a-tree/",
      },
      {
        problemId: "level-order",
        title: "Binary Tree Level Order Traversal",
        difficulty: "Medium",
        youtubeLink: "https://www.youtube.com/results?search_query=binary+tree+level+order+traversal",
        practiceLink: "https://leetcode.com/problems/binary-tree-level-order-traversal/",
        articleLink: "https://www.geeksforgeeks.org/level-order-tree-traversal/",
      },
      {
        problemId: "serialize-tree",
        title: "Serialize and Deserialize Binary Tree",
        difficulty: "Tough",
        youtubeLink: "https://www.youtube.com/results?search_query=serialize+deserialize+binary+tree",
        practiceLink: "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/",
        articleLink: "https://www.geeksforgeeks.org/serialize-deserialize-binary-tree/",
      },
    ],
  },
  {
    topicId: "dynamic-programming",
    title: "Dynamic Programming",
    description: "Memoization and tabulation patterns for optimization problems.",
    order: 5,
    problems: [
      {
        problemId: "climbing-stairs",
        title: "Climbing Stairs",
        difficulty: "Easy",
        youtubeLink: "https://www.youtube.com/results?search_query=climbing+stairs+leetcode+dp",
        practiceLink: "https://leetcode.com/problems/climbing-stairs/",
        articleLink: "https://www.geeksforgeeks.org/count-ways-reach-nth-stair/",
      },
      {
        problemId: "coin-change",
        title: "Coin Change",
        difficulty: "Medium",
        youtubeLink: "https://www.youtube.com/results?search_query=coin+change+leetcode+dp",
        practiceLink: "https://leetcode.com/problems/coin-change/",
        articleLink: "https://www.geeksforgeeks.org/coin-change-dp-7/",
      },
      {
        problemId: "longest-increasing-subsequence",
        title: "Longest Increasing Subsequence",
        difficulty: "Tough",
        youtubeLink: "https://www.youtube.com/results?search_query=longest+increasing+subsequence+dp",
        practiceLink: "https://leetcode.com/problems/longest-increasing-subsequence/",
        articleLink: "https://www.geeksforgeeks.org/longest-increasing-subsequence-dp-3/",
      },
    ],
  },
];
